-- URLSTORAGE DB CREATIION QUERY
CREATE TABLE URLSTORAGE (
    URLID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORIGINALURL VARCHAR(255) NOT NULL,
    SHORTURL VARCHAR(255) NOT NULL UNIQUE,
    CREATIONDATE VARCHAR(255) NOT NULL,
    EXPIRYDATE VARCHAR(255),
    STATUS VARCHAR(255) NOT NULL,
    IPADDRESS VARCHAR(255) NOT NULL,
    VISITS INT NOT NULL,
    LASTACCESSEDDATE VARCHAR(255),
    LASTACCESSEDIP VARCHAR(255),
    QRCODE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TAGS VARCHAR(255),
    CREATEDBY VARCHAR(255)
);



